// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * =================================================================================
 * DANGER: ADMIN CLIENT - À N'UTILISER QUE CÔTÉ SERVEUR
 * =================================================================================
 * Ce client Supabase est initialisé avec une clé de service (service_role key),
 * lui donnant des privilèges d'administration complets sur votre base de données.
 * 
 * NE JAMAIS UTILISER CE CLIENT CÔTÉ CLIENT (DANS UN NAVIGATEUR)
 * 
 * L'exposer côté client reviendrait à donner les clés de votre base de données
 * à n'importe qui. Utilisez-le uniquement dans un environnement sécurisé côté serveur,
 * comme les Edge Functions de Supabase, les fonctions serverless, ou un backend dédié.
 * 
 * Si ce code est exécuté dans le navigateur, il y a une faille de sécurité majeure.
 * =================================================================================
 */
export const supabaseAdmin = SUPABASE_SERVICE_ROLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })
  : supabase; // Fallback to regular client if service key is not set

// Log a warning if the admin client is used in a browser environment
if (typeof window !== 'undefined' && SUPABASE_SERVICE_ROLE_KEY) {
  console.warn(
    'DANGER ZONE: La clé de service Supabase (supabaseAdmin) est exposée côté client. ' +
    'Ceci est une faille de sécurité majeure. Utilisez-la uniquement côté serveur.'
  );
}